### ISSUE TITLE
expfit doesnt appear in INDEX file

### ISSUE THREAD

**Issue by lostbard** [gnu-octave/statistics#52] opened 2022-09-30 16:12 UTC
same with explike, expstat

**Comment by lostbard** [comment] 2022-09-30 16:14
I belive see also in them should be deftypefn block ?

**Comment by lostbard** [comment] 2022-09-30 16:22
And for expfit, running help:

```
> help expfit
octave-help-VwzFqQ:174: misplaced {
octave-help-VwzFqQ:174: misplaced }
octave-help-VwzFqQ:174: misplaced {
octave-help-VwzFqQ:174: misplaced }
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...
```

**Comment by pr0m1th3as** [comment] 2022-09-30 16:43
I can't reproduce the warning with formating. It appears properly on my machines.
```
help expfit
'expfit' is a function from the file /home/promitheas/.local/share/octave/api-v57/packages/statistics-1.5.0/expfit.m

 -- Function File: MU = expfit (S)
 -- Function File: [MU, CI] = expfit (S)
 -- Function File: [MU, CI] = expfit (S, ALPHA)
 -- Function File: ... = expfit (S, ALPHA, C)
 -- Function File: ... = expfit (S, ALPHA, C, F)

     Estimate the mean of the exponential probability distribution
     function from which sample data S has been taken.  S is expected to
     be a non-negative vector.  If S is an array, the mean will be
     computed for each column of S.  If any elements of S are NaN, that
     vector's mean will be returned as NaN.
```

Yes not every function is listed in INDEX file. This will be address in forthcoming release. The plan is to assemble the missing functions per group so we can make a timeplan as to how and when they will be included.

**Comment by lostbard** [comment] 2022-09-30 16:49
The misplaced {} is due to the help text being expanded to:

```
@xseealso{expcdf, expinv, explike, exppdf, exprnd, expstat}
@@seealso{expstat, exprnd, expcdf, expinv}
```

**Comment by pr0m1th3as** [comment] 2022-09-30 17:15
It also works correctly in octave 6

**Comment by lostbard** [comment] 2022-09-30 17:41
for the { } warning, octave bug #63141 was created

**Comment by mmuetzel** [comment] 2022-10-11 11:27
Does this work again with a new enough version of Octave 8?

**Comment by pr0m1th3as** [comment] 2022-11-04 15:13
Updated INDEX with existing functions including evfit

**Closed by pr0m1th3as** 2022-11-04 15:13 UTC
